# Generated by Django 4.1.3 on 2022-12-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField()),
                ('year', models.CharField(max_length=200, null=True)),
                ('mileage', models.CharField(max_length=200, null=True)),
                ('trans', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
