# Generated by Django 4.1.3 on 2022-12-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_car_image1_car_image2_car_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='desc',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
