# Generated by Django 4.1.3 on 2022-12-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_car_desc_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date1',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date2',
            field=models.DateField(null=True),
        ),
    ]
