# Generated by Django 4.1.3 on 2022-12-11 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_booking_date1_alter_booking_date2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='booking',
        ),
    ]
