# Generated by Django 4.1.3 on 2022-12-11 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='car',
            name='image3',
        ),
    ]
