# Generated by Django 4.1.3 on 2022-12-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_customer_user_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='adults',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='children',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_location',
            field=models.CharField(blank=True, choices=[('Kottayam', 'Kottayam'), ('Changanacherry', 'Changanacherry')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_location',
            field=models.CharField(blank=True, choices=[('Kottayam', 'Kottayam'), ('Changanacherry', 'Changanacherry')], max_length=200, null=True),
        ),
    ]
