# Generated by Django 4.1.3 on 2022-12-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_booking_adults_booking_children_booking_pickup_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='adults',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='children',
        ),
        migrations.AddField(
            model_name='booking',
            name='special_request',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
