# Generated by Django 4.1.3 on 2022-12-12 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_booking_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
