# Generated by Django 4.1.3 on 2022-12-12 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('date_booked', models.DateField(auto_now_add=True, null=True)),
                ('pickup_date', models.CharField(blank=True, max_length=200, null=True)),
                ('return_date', models.CharField(blank=True, max_length=200, null=True)),
                ('pickup_location', models.CharField(blank=True, max_length=200, null=True)),
                ('return_location', models.CharField(blank=True, max_length=200, null=True)),
                ('special_request', models.CharField(blank=True, max_length=500, null=True)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.car')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.customer')),
            ],
        ),
    ]
