# Generated by Django 3.2.19 on 2023-05-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date_booked',
        ),
        migrations.AddField(
            model_name='booking',
            name='date_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
