# Generated by Django 3.2.19 on 2023-05-09 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20230509_1106'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customer',
        ),
    ]
